version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "01:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.6.2
    - 12.6.3
    - 12.7.0
    - 12.7.1
    - 12.7.2
    - 12.7.3
    - 12.7.4
    - 12.8.0
    - 12.8.1
    - 12.8.2
    - 12.8.3
    - 13.0.0
    - 13.0.1
    - 13.0.10
    - 13.0.11
    - 13.0.12
    - 13.0.13
    - 13.0.14
    - 13.0.15
    - 13.0.16
    - 13.0.2
    - 13.0.3
    - 13.0.4
    - 13.0.5
    - 13.0.6
    - 13.0.7
    - 13.0.8
    - 13.0.9
    - 13.1.0
    - 13.1.1
    - 13.1.2
    - 13.1.3
    - 13.1.5
    - 13.1.6
    - 13.1.7
  - dependency-name: react-datepicker
    versions:
    - 3.4.1
    - 3.5.0
    - 3.6.0
    - 3.7.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
    - 5.11.9
  - dependency-name: react-bootstrap
    versions:
    - 1.4.3
    - 1.5.0
    - 1.5.1
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
    - 11.2.4
    - 11.2.5
  - dependency-name: "@material-ui/core"
    versions:
    - 4.11.3
  - dependency-name: "@fortawesome/free-solid-svg-icons"
    versions:
    - 5.15.2
  - dependency-name: "@fortawesome/fontawesome-svg-core"
    versions:
    - 1.2.34
  - dependency-name: "@fortawesome/free-brands-svg-icons"
    versions:
    - 5.15.2
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
- package-ecosystem: npm
  directory: "/backend"
  schedule:
    interval: daily
    time: "01:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mongoose
    versions:
    - 5.11.14
    - 5.11.15
    - 5.11.16
    - 5.11.17
    - 5.11.18
    - 5.11.19
    - 5.11.20
    - 5.12.0
    - 5.12.1
    - 5.12.2
    - 5.12.3
    - 5.12.5
    - 5.12.6
  - dependency-name: react-bootstrap
    versions:
    - 1.4.3
    - 1.5.0
    - 1.5.1
  - dependency-name: "@fortawesome/fontawesome-svg-core"
    versions:
    - 1.2.34
  - dependency-name: "@fortawesome/free-solid-svg-icons"
    versions:
    - 5.15.2
  - dependency-name: lodash
    versions:
    - 4.17.20
- package-ecosystem: pip
  directory: "/requirements.txt"
  schedule:
    interval: daily
    time: "01:00"
  open-pull-requests-limit: 10
